org.slf4j.simpleLogger.defaultLogLevel=error

org.slf4j.simpleLogger.log.io.github.bonigarcia.wdm=off

org.slf4j.simpleLogger.log.org.openqa.selenium=off
org.slf4j.simpleLogger.log.org.openqa.selenium.devtools=off
org.slf4j.simpleLogger.log.org.openqa.selenium.chromium=off

org.slf4j.simpleLogger.log.org.openqa.selenium.devtools.CdpVersionFinder=off
org.slf4j.simpleLogger.log.org.openqa.selenium.chromium.ChromiumDriver=off

org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false